import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import {
  ExportToXlsx,
  IColumnDef,
  IExportToXlsxConfig,
} from "@/Utils";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  interface Idata {
    name: string;
    age: number;
    email: string;
  }

  const handler = () => {
    const data: Idata[] = [
      { name: "jeka", age: 20, email: "jeka@yopmail.com" },
      { name: "kobi", age: 25, email: "kobi@yopmail.com" },
      { name: "yosi", age: 18, email: "yosi@yopmail.com" },
    ];

    const cols: IColumnDef<Idata>[] = [
      { key: "name", header: "name", width: 20 },
      { key: "age", header: "age", width: 20 },
      { key: "email", header: "email", width: 20 },
    ];

    const config: IExportToXlsxConfig = {
      filename: "test",
      headerStyles:{bgColor:"00000", fontProps:{color:"ff9999", size:22, bold:true}},
      cellStyles:{bgColor:"ff9999", borderProps:{color:"00000", variant:'thick'}}
    };

    ExportToXlsx<Idata>(data, cols, config);

  };

  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <button onClick={handler}>click</button>
    </>
  );
}
